/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PromoCodesRouteImport } from './routes/promo-codes'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropFirmsIndexRouteImport } from './routes/prop-firms.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropFirmsSlugRouteImport } from './routes/prop-firms.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCodesRoute = PromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmsIndexRoute = PropFirmsIndexRouteImport.update({
  id: '/prop-firms/',
  path: '/prop-firms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmsSlugRoute = PropFirmsSlugRouteImport.update({
  id: '/prop-firms/$slug',
  path: '/prop-firms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/search': typeof SearchRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/prop-firms/': typeof PropFirmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/search': typeof SearchRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/prop-firms': typeof PropFirmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/search': typeof SearchRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/prop-firms/': typeof PropFirmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/payouts'
    | '/promo-codes'
    | '/search'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin/'
    | '/prop-firms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/payouts'
    | '/promo-codes'
    | '/search'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin'
    | '/prop-firms'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/payouts'
    | '/promo-codes'
    | '/search'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin/'
    | '/prop-firms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  PayoutsRoute: typeof PayoutsRoute
  PromoCodesRoute: typeof PromoCodesRoute
  SearchRoute: typeof SearchRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PropFirmsSlugRoute: typeof PropFirmsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PropFirmsIndexRoute: typeof PropFirmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-codes': {
      id: '/promo-codes'
      path: '/promo-codes'
      fullPath: '/promo-codes'
      preLoaderRoute: typeof PromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firms/': {
      id: '/prop-firms/'
      path: '/prop-firms'
      fullPath: '/prop-firms/'
      preLoaderRoute: typeof PropFirmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firms/$slug': {
      id: '/prop-firms/$slug'
      path: '/prop-firms/$slug'
      fullPath: '/prop-firms/$slug'
      preLoaderRoute: typeof PropFirmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  PayoutsRoute: PayoutsRoute,
  PromoCodesRoute: PromoCodesRoute,
  SearchRoute: SearchRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  PropFirmsSlugRoute: PropFirmsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PropFirmsIndexRoute: PropFirmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
